version: 0.2

env:
  variables:
    ENV: "production"

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Setting up environment for production BDD testing..."
      - export ENV=production
      - export FLASK_ENV=production
      - nohup python app.py & # Start Flask app in the background
      - sleep 5

  build:
    commands:
      - mkdir -p test-results
      - echo "Running BDD tests..."
      - behave --format json.pretty --outfile test-reports/behave-report.json
      - pwd

  post_build:
    commands:
      - echo "Production BDD testing completed"
      - echo "Uploading test results to S3..."
      - aws s3 cp test-results/ s3://flaskbddtests/test-results/ --recursive

reports:
  test_reports:
    files:
      - test-reports/behave-report.json
    base-directory: test-results
    file-format: JSON
    discard-paths: yes

artifacts:
  files:
    - test-reports/behave-report.json
  discard-paths: yes
